XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates
XCODE_USER_SNIPPETS_DIR=~/Library/Developer/Xcode/UserData/CodeSnippets

TEMPLATES_DIR=Coordinate\ Clean\ Swift

dns:
	sudo killall -HUP mDNSResponder && echo "has been dns cleared successfully"
